### ISSUE TITLE
Add Jupyter notebook for validation of visual elements of minima finding.

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/solvation-analysis#26]
The minima finding element of the tests requires manual visual validation of the minima identified algorithmically. This process should be easily repeatable and IMO should be put into a jupyter-notebook somewhere near the tests.

**Comment by orioncohen** [comment]
I implemented a basic jupyter notebook for visualizing the rdfs in PR #25. It is in the root directory of the package. However, I am not sure this is the best approach for visual validation.

1. I had to put the jupyter notebook at the root of the package directory so that I could call 
```from solvation_analysis.rdf_partser import interpolation fit```
When I tried to put the Jupyter notebook near the data, I got a `ModuleNotFound` error. Perhaps there is a workaround?

2. Since the jupyter notebook is not in the package itself, I can't use any of the import infrastructure that I built up using pytest. 

My preference would be to leave this jupyter notebook around as an alternative option, but to mainly use the test_plot_interpolation_fit function for validation in testing. It is super easy to use in my workflow, automatically imports the data from `conftest.py`, and fits in with the rest of the testing.

Maybe some basic jupyter notebook examples of the interpolation scheme would be a better fit for the tutorial, rather than testing?

**Comment by hmacdope** [comment]
That's perfect for now, no need for anything complicated. I just wanted a resource that can be picked up easily by others (including myself) to easily figure out what the rdfs and minima look like. As you say, we can add some more detailed stuff in tutorials later. I'll close this when the notebook is merged as part of #25.
