### ISSUE TITLE
Investigate atomgroup based core data structure.

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/solvation-analysis#32]
Currently we use a pandas dataframe to keep track of all the solute-solvent pairs (It can be very very big). The other option is to use a list of lists of AtomGroups, ie one for each solvating atom per frame.

Even just writing it out this sounds expensive, but might be worth investigating with some toy benchmarks.

**Comment by orioncohen** [comment]
Now that the package is more mature, I think this is largely out of the question. I now consider the data-frame centric structure of `solvation_analysis` to be a major strength, both in terms of speed and flexibility. Additionally, since the data frame stores the `res_id` of each coordinating species, the AtomGroups can be reconstructed relatively easily.

With that in mind, I'm going to close this.

**Comment by hmacdope** [comment]
Agree entirely.
