### ISSUE TITLE
Feature Request: pass Solution.run() kwargs to RDF

### ISSUE THREAD

**Issue by rkingsbury** [MDAnalysis/solvation-analysis#46]
Currently `Solution.run()` accepts kwargs `start`, `stop`, `step`, and `verbose` just like `MDAnalysis.analysis.rdf.InterRDF`. However, the kwargs passed to `Solution.run()` are not passed to the underlying RDF call; rather you have to use a separate `rdf_run_kwargs` argument when instantiating `Solution`. 

Based on my limited understanding so far, I can't think of a reason why you would ever want the two _not_ to match. There's probably no reason for your RDF to have a higher resolution than your analysis, right? If I'm right (and please correct me if I'm wrong), would it be possible to pass `Solution.run()` kwargs directly to the internal RDF calls?

**Comment by orioncohen** [comment]
Thanks for raising this @rkingsbury!

I can't imagine a reason that the `start` and `stop` args would be different but `step` might need to be.  I added a distinction between the two because I worried that either the `rdf.run()` call or the `solution.run()` call would be too time consuming and a user might want to use a higher `step`. For very large simulations, I think this could still be convenient but I have not personally used different values.

That said, it's probably better to use the same parameters for both as a default. At the least, the `Solution` class should be updated to use the values from `solution.run()` as a default for the `InterRDF.run()` call.

**Comment by hmacdope** [comment]
The problem here is that `InterRDF.run()` happens in `_prepare`, before `Solution.run()` is called which means it cannot know about what kwargs are provided. We can either homogenise the kwargs between them or just leave it the way it is. Open to any other ideas but would be good to resolve for Roadmap to 0.2
